{% set version = "1.0.6" %}

package:
  name: rcssmin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rcssmin/rcssmin-{{ version }}.tar.gz
  sha256: ca87b695d3d7864157773a61263e5abb96006e9ff0e021eff90cbe0e1ba18270

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - django >=1.8

test:
  imports:
    - rcssmin

about:
  home: https://github.com/ndparker/rcssmin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast CSS minifier for Python'
  description: |
    RCSSmin is a CSS minifier written in python. The minifier is based on the semantics of the YUI compressor, 
    which itself is based on the rule list by Isaac Schlueter. This module is a re-implementation aiming for 
    speed instead of maximum compression, so it can be used at runtime (rather than during a preprocessing step). 
    RCSSmin does syntactical compression only (removing spaces, comments and possibly semicolons). It does not 
    provide semantic compression (like removing empty blocks, collapsing redundant properties etc). It does, 
    however, support various CSS hacks (by keeping them working as intended).
  doc_url: http://opensource.perlig.de/rcssmin/doc-1.0/index.html
  dev_url: https://github.com/ndparker/rcssmin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
