{% set name = "rcssmin" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rcssmin-{{ version }}.tar.gz
  sha256: 4f9400b4366d29f5f5446f58e78549afa8338e6a59740c73115e9f6ac413dc64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - rcssmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ndparker/rcssmin
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - bench/LICENSE.cssmin
  summary: 'Fast CSS minifier for Python'
  description: |
    RCSSmin is a CSS minifier written in python. The minifier is based on the semantics of the YUI compressor, 
    which itself is based on the rule list by Isaac Schlueter. This module is a re-implementation aiming for 
    speed instead of maximum compression, so it can be used at runtime (rather than during a preprocessing step). 
    RCSSmin does syntactical compression only (removing spaces, comments and possibly semicolons). It does not 
    provide semantic compression (like removing empty blocks, collapsing redundant properties etc). It does, 
    however, support various CSS hacks (by keeping them working as intended).
  doc_url: http://opensource.perlig.de/rcssmin/doc-1.0/index.html
  dev_url: https://github.com/ndparker/rcssmin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
