travis:
  secure:
    BINSTAR_TOKEN: sQimGkWe9dh1TNWRUh+WszNiGf7kHNFB5U99AlJh0Y9w70s0/yZHwHRVT8hzhiCairkew9wpR1w7J6+patLYLk6t0bKSD15zsQnss3Mty5e55bpqh7k7JDEN8RmCf7Wvxv28knIccToo9LBcGd7NPdTPqkVTEiNWvxQugO9LPVSE2QNZwZ6dIssa6xtzn8O1jrZiGYYr4DDc6KMiSRpW69my/TRq92IJSKmjgH7s99jntG0GZZDBMev/56T8Ka0z3wghIWCa/WixCKxW9oLFyczSL6nkd3Byd6uQ8CVPt7PTpo0V+enyYFzJdkzp24EzFCd5kZM9xxFf6SwHrFZFfui8XAYhrOP+Vp5LdECAQBIO52reu66z0MuJtAWwrRfuUVaItJqqnddUjBi18wJ+0kzO1T7KhvokJFQYOnDPFnRyWBtLcVHyjSa910lwT9h1fw4ZmQoKbFpr1ZcVx9GFk4CzfCLcLa0YPvjEzAA8DTKrBtokmGymU3KbUmmz8Ww/tXeVkOtSOgFfBsB86Ggs00mvI7Z1i72AOt1xrQcdCGElzNU4wMlFoUZnqICoQbEfeSUnwqVq52RO3zULVjTAiw9P0i/NSGNdFKzUDrT13D8rhpE8Gd7/r3vcicjJHRKZ6majlbOGl8zqjLwOcNJvRYZZEnDZNtWJuGOGCmCpZj4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
